version: "3.8"
services:
  client-app:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  server-app:
    container_name: server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
